name: Run Python Script

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ACCOUNT: ${{ secrets.ACCOUNT }}
      WAREHOUSE: ${{ secrets.WAREHOUSE }}
      DATABASE: ${{ secrets.DATABASE }}
      SCHEMA: ${{ secrets.SCHEMA }}
      STAGE: ${{ secrets.STAGE }}
      USER: ${{ secrets.USER }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create private key file
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.p8
          chmod 600 private_key.p8

      - name: Run script
        run: python main.py
